steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull $REPO_FULL_NAME:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '$REPO_FULL_NAME:latest',
    '--cache-from', '$REPO_FULL_NAME:latest',
    '.'
  ]
images: ['$REPO_FULL_NAME:latest']